name: Deploy site

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install deterministic zip
        run: |
          wget https://github.com/timo-reymann/deterministic-zip/releases/latest/download/deterministic-zip_linux-amd64
          chmod +x deterministic-zip_linux-amd64
          sudo mv deterministic-zip_linux-amd64 /usr/local/bin/zip

      - name: Package files
        run: |
          cd archive
          chmod +x build.sh
          ./build.sh

      # to get README.md to webpage as well as GitHub's UI
      - name: Pre-generation of directory listing
        run: cp README.md out/README.md

      - name: Github Pages Directory Listing
        uses: jayanta525/github-pages-directory-listing@v4
        with:
          FOLDER: out

      # these shouldn't be in apindex, but need to be in repo root for GitHub Pages
      - name: Pre-generation of directory listing
        run: |
          mkdir public
          cp -r out/* public
          cp CNAME public
          touch public/.nojekyll 

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          repository-name: DS-Homebrew/flashcard-archive-web
          token: ${{ secrets.WEB_PUSH_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: public # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branchimage: ubuntu:bionic
