name: Deploy site

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  doc-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: recursive
          fetch-depth: 1

      # to get README.md to webpage as well as GitHub's UI
      - name: Pre-generation of directory listing
        run: cp README.md files/README.md

      - name: Github Pages Directory Listing
        uses: jayanta525/github-pages-directory-listing@v3
        with:
          FOLDER: files

      # these shouldn't be in apindex, but need to be in repo root for GitHub Pages
      - name: Pre-generation of directory listing
        run: |
          mkdir public
          cp -r files/* public
          cp CNAME public
          touch public/.nojekyll 

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branchimage: ubuntu:bionic
